### ISSUE TITLE
Makefile Problem

### ISSUE THREAD

**Issue by Amirmohammadkazemi** [bistcuite/unox-os#1]
This make file have problem

Error 127

![image](https://user-images.githubusercontent.com/78997499/148766704-f7411569-ea70-4814-ab4a-70d67595ec92.png)

**Comment by bistcuite** [comment]
Make sure `nasm` installed.

**Comment by Amirmohammadkazemi** [comment]
Yes nasm instaled.
![image](https://user-images.githubusercontent.com/78997499/148909938-9eb7a9ba-31a4-4b98-ab47-3a0efff42a11.png)

**Comment by bistcuite** [comment]
You should install gcc cross compiler toolchain.
If your gcc supports `i386 elf` you can rename `x86_64-elf-*` in makefile(but installing cross compiler is better and recommended)

[x86_64-elf-gcc for arch](https://aur.archlinux.org/packages/x86_64-elf-gcc/)
